sonar.projectKey=event-tracker
sonar.working.directory=D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker
sonar.pullrequest.cache.basepath=D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker

679659F6-8FCF-4418-83F7-09D9447C0FC3.sonar.projectKey=event-tracker:679659F6-8FCF-4418-83F7-09D9447C0FC3
679659F6-8FCF-4418-83F7-09D9447C0FC3.sonar.projectName=event-tracker
679659F6-8FCF-4418-83F7-09D9447C0FC3.sonar.projectBaseDir=D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker
679659F6-8FCF-4418-83F7-09D9447C0FC3.sonar.sourceEncoding=utf-8
679659F6-8FCF-4418-83F7-09D9447C0FC3.sonar.tests=
679659F6-8FCF-4418-83F7-09D9447C0FC3.sonar.sources=\
"D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\AuditTrailAttribute .cs",\
"D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\EventLog.cs",\
"D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\EventTracker.cs",\
"D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\Program.cs",\
"D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\UserActions.cs",\
"D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\obj\\event-tracker.csproj.nuget.dgspec.json",\
"D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\obj\\project.assets.json",\
"D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\bin\\Debug\\net10.0\\event-tracker.deps.json",\
"D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\bin\\Debug\\net10.0\\event-tracker.runtimeconfig.json",\
"D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\obj\\Debug\\net10.0\\event-tracker.sourcelink.json"

679659F6-8FCF-4418-83F7-09D9447C0FC3.sonar.cs.analyzer.projectOutPaths=\
"D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\.sonarqube\\out\\0"
679659F6-8FCF-4418-83F7-09D9447C0FC3.sonar.cs.roslyn.reportFilePaths=\
"D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\.sonarqube\\out\\0\\Issues.json"
679659F6-8FCF-4418-83F7-09D9447C0FC3.sonar.cs.scanner.telemetry=\
"D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\.sonarqube\\out\\0\\Telemetry.json"

679659F6-8FCF-4418-83F7-09D9447C0FC3.sonar.working.directory=D:\\BridgeLabz-Training\\generics-csharp-practice\\scenario-based\\event-tracker\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=679659F6-8FCF-4418-83F7-09D9447C0FC3

